export const LAUNCH_DATA_FETCH_START = "LAUNCH_DATA_FETCH_START";
export const LAUNCH_DATA_FETCH_SUCCESS = "LAUNCH_DATA_FETCH_SUCCESS"; 
export const LAUNCH_DATA_FETCH_ERROR = "LAUNCH_DATA_FETCH_ERROR";